src/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home-index'),
    path('login/', views.login_user, name='home-login'),
    path('logout/', views.logout_user, name='home-logout'),
    path('register/', views.register, name='home-register'),
    path('contact/', views.contact, name='home-contact'),
    path('places/<int:place_id>/', views.placeinfo, name='place-info'),
    path('places/<int:place_id>/favorite/', views.favorite, name='place-favorite'),
    path('places/<int:place_id>/unfavorite/', views.unfavorite, name='place-unfavorite'),
    path('places/', views.places, name='places-index'),
    path('places/new/', views.add_place, name='places-new'),
    path('profile/<int:user_id>/', views.profile, name='profile-index'),
    path('profile/<int:user_id>/edit/', views.edit_profile, name='profile-edit'),
]

src/tourism_time/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/home/models.py
from django.db import models
from django.contrib.auth.models import User
from math import floor
from django.utils.timezone import now

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatars/", default="/avatars/default-avatar.png")

    bookings = models.ManyToManyField('Place', through='Ticket')
    favorites = models.ManyToManyField('Place', blank=True, related_name='user_favprotes')
    
    last_seen = models.DateTimeField(default=now())

    def __str__(self):
        return "%s %s (%s)" %(self.user.first_name, self.user.last_name, self.user.username)


class Town(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=25)
    icon = models.ImageField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Place(models.Model):
    posted_by = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    map_id = models.CharField(max_length=500)

    town = models.ForeignKey(Town, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    phone_number = models.CharField(max_length=25)
    website = models.CharField(max_length=120, default="Not specified", blank=True)
    # location_lat = models.DecimalField(max_digits=15, decimal_places=9, verbose_name="Location Latitude")
    # location_lng = models.DecimalField(max_digits=15, decimal_places=9, verbose_name="Location Longitude")
    opening_hours = models.CharField(max_length=50, default="Not specified", blank=True)
    
    description = models.TextField()
    is_approved = models.BooleanField(verbose_name="Approved?", default=False)

    rating = models.DecimalField(max_digits=3, decimal_places=2, default=0, blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def get_place_new_rating(self, rating):
        # reviews = Review.objects.filter(place=self)
        # totalReviews = reviews.count()
        # avg_rating = ((self.rating * totalReviews) + rating) / (totalReviews + 1)
        reviews = Review.objects.filter(place=self)
        five = reviews.filter(rating=Rating.objects.get(stars=5))
        four = reviews.filter(rating=Rating.objects.get(stars=4))
        three = reviews.filter(rating=Rating.objects.get(stars=3))
        two = reviews.filter(rating=Rating.objects.get(stars=2))
        one = reviews.filter(rating=Rating.objects.get(stars=1))
        avg_rating = (5*five.count() + 4*four.count() + 3*three.count() + 2*two.count() + 1*one.count())
        avg_rating = avg_rating / reviews.count()
        return avg_rating

    def get_place_abs_rating(self):
        return floor(self.rating) 
    




class Ticket(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    expire_date = models.DateField()
    price = models.PositiveIntegerField()

    def __str__(self):
        return "%s's ticket for %s" %(self.profile, self.place)


class Image(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    image = models.ImageField()
    
    def __str__(self):
        return "%s's Image (%s)" %(self.place, self.id)

class Rating(models.Model):
    stars = models.PositiveIntegerField()
    text = models.CharField(max_length=25)
    image = models.ImageField(default="static/home/images/rating_stars/0_stars.png")

    def __str__(self):
        return "%s (%s)" %(self.text, self.stars)

class Review(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    rating = models.ForeignKey(Rating, on_delete=models.CASCADE)
    comment = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s's review on: %s" %(self.profile, self.place)

src/home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Place, Review

class UserRegisterForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=100)
    last_name = forms.CharField(label='Last name', max_length=100)
    username = forms.CharField(label='Username', max_length=25)
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    p_confirm = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(UserRegisterForm, self).clean()
        password = cleaned_data.get("password")
        p_confirm = cleaned_data.get("p_confirm")

        if password != p_confirm:
            raise forms.ValidationError("Your password doesn't match, please check again.")


class AddPlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        # Show all fields except is_approved
        exclude = ['is_approved']


class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']

src/home/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Place, Image, Review, Town, Profile, Rating, Category
from django.contrib.auth.models import User
from .forms import UserRegisterForm, AddPlaceForm, AddReviewForm, EditProfileForm

def index(request):
    categories = get_list_or_404(Category)
    #places = get_list_or_404(Place)
    #reviews = get_list_or_404(Review)
	
    most_recent = Place.objects.filter(is_approved=True).order_by("-post_date")[:4]
    most_popular = Place.objects.filter(is_approved=True).order_by("-views")[:4]

    context = {
        'home_page': "active",
        'categories': categories,
		'most_popular': most_popular,
		'most_recent': most_recent,
    }
    
    return render(request, 'home/index.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(request.POST['next'])
        
    context = {
        'title': 'Sign In',
        'login_page': 'active',
        'next': request.GET.get('next', reverse('home-index'))
    }

    return render(request, 'home/login.html', context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home-index'))


def register(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UserRegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            user = User.objects.create_user(
                form.cleaned_data['username'],
                form.cleaned_data['email'],
                form.cleaned_data['password']
            )

            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            
            user.save()

            login(request, user)
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('home-index'))
    else:
        form = UserRegisterForm()

    context = {
        'title': 'Sign Up',
        'register_page': 'active',
        'form': form
    }
    return render(request, 'home/register.html', context)


def contact(request):
    context = {
        'title': 'Contact Us',
        'contact_page': 'active'
    }
    return render(request, 'home/contact.html', context)


def placeinfo(request, place_id):
    place = get_object_or_404(Place, id=place_id)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AddReviewForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            try:
                new_review = Review.objects.get(place=place, profile=request.user.profile)
                new_review.comment = request.POST['comment']
            except Review.DoesNotExist:
                new_review = form.save(commit=False)
                new_review.place = Place.objects.get(id=place_id)
                new_review.profile = request.user.profile
                messages.success(request, 'Your Review has been added.')

            new_review.rating = Rating.objects.get(stars=request.POST['rating'])
            new_review.save()
            place.rating = place.get_place_new_rating(new_review.rating.stars)
            place.save()

            
        else:
            print(form.errors)

    reviews = Review.objects.filter(place=place_id).order_by('-datetime')

    images = Image.objects.filter(place=place_id)

    if request.user.is_authenticated:
        try:
            review = Review.objects.get(place=place, profile=request.user.profile)
        except Review.DoesNotExist:
            review = False

        if review:
            form = AddReviewForm(instance=review)
        else:
            form = False
    else:
        form = False

    if request.user.is_authenticated:
        favorite_state = request.user.profile.favorites.filter(id=place.id).exists()
    else:
        favorite_state = False

    # Count view
    place.views = place.views+1
    place.save()

    context = {
        'title': place.name,
        'browse_page': 'active',
        'place': place,
        'reviews': reviews,
        'images': images,
        'form': form,
        'is_favoured': favorite_state
    }
    return render(request, 'home/placeinfo.html', context)

def places(request):
    category = request.GET.get('category')
    
    if category:
        places = Place.objects.filter(category=category, is_approved=True).order_by('-post_date')
        current_category = Category.objects.get(id=category)
    else:
        places = Place.objects.filter(is_approved=True).order_by('-post_date')
        current_category = False

    paginator = Paginator(places, 5)

    page = request.GET.get('page')
    places = paginator.get_page(page)

    categories = get_list_or_404(Category)

    context = {
        'title': 'Places',
        'browse_page': 'active',
        'places': places,
        'categories': categories,
        'current_category': current_category
    }
    return render(request, 'home/places.html', context)

@login_required
def add_place(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AddPlaceForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # Save new place
            new_place = form.save()
            messages.success(request, 'The Place has been added.')
            # Get uploaded pictures as a list
            pictures = request.FILES.getlist('files')

            # Loop over them and save each one
            for pic in pictures:
                image = Image(place=new_place, image=pic)
                image.save()


    form = AddPlaceForm()

    context = {
        'title': 'Places: Add New',
        'browse_page': 'active',
        'form': form,
        'profile': get_object_or_404(Profile, user=request.user.id)
    }
    return render(request, 'home/add_place.html', context)


def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    profile = Profile.objects.get(user = user)

    state = "active" if request.user.id == user_id else ""

    context = {
        'title': 'Profile: %s' %(user.username),
        'user_profile': state,
        'profile': profile,
    }
    return render(request, 'home/profile.html', context)

@login_required
def edit_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    profile = Profile.objects.get(user=user)

    # Prevent someone else from editing others profile
    if request.user != user:
        return HttpResponseRedirect(reverse('profile-index', args=[request.user.id]))

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = EditProfileForm(request.POST, instance=user)
        # check whether it's valid:
        if form.is_valid():
            #user.username = request.POST['username']
            #user.first_name = request.POST['first_name']
            #user.last_name = request.POST['last_name']
            user.save()
            #User.objects.filter(id=user_id).update(username=request.POST['username'], first_name=request.POST['first_name'], last_name=request.POST['last_name'])

            #print(request.FILES['avatar'])
            # Check for avatar update
            if request.FILES.get('avatar', False):
                profile.avatar = request.FILES['avatar']
                profile.save()
                #profile.update(avatar=request.FILES['avatar'])

            messages.success(request, 'Your profile has been updated successfully.')
            return HttpResponseRedirect(reverse('profile-index', kwargs={'user_id': request.user.id}))
        else:
            print(form.errors)

    form = EditProfileForm(instance=user)

    context = {
        'title': 'Profile Edit: %s' %(user.username),
        'user_profile': 'active',
        'profile': profile,
        'form': form,
		'user': user,
    }
    return render(request, 'home/edit_profile.html', context)

def favorite(request, place_id):
    user = get_object_or_404(User, id=request.user.id)
    profile = Profile.objects.get(user = user)

    place = Place.objects.get(id=place_id)
    profile.favorites.add(place)
    messages.success(request, 'This place has been added to your favourites.')

    next = request.GET['next']
    if next:
       return HttpResponseRedirect(next)
    else: 
        return HttpResponseRedirect(reverse('places-index'))

def unfavorite(request, place_id):
    user = get_object_or_404(User, id=request.user.id)
    profile = Profile.objects.get(user = user)

    place = Place.objects.get(id=place_id)
    profile.favorites.remove(place)
    messages.success(request, 'This place has been removed from your favourites.')
    

    return HttpResponseRedirect( request.GET.get('next', reverse('places-index')) )

src/home/templates/home/add_place.html
{% extends 'home/base.html' %}
{% block content %}
{% load static %}
<div class="flex-grow-1" id="login" style="height: 680px;">
    <div class="container h-100">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="card my-auto text-light" style="height: auto; width: 850px;">
                <div class="card-header">
                    <center>
                        <h3>Add New Place</h3>
                    </center>
                </div>
				<!-- Message success -->
				{% if messages %}
				<div class="alert alert-success col-10 col align-self-center">
					{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}><strong>Success! </strong>{{ message }} <a href="{% url 'places-index' %}" class="alert-link">Browse Places</a></li>
					{% endfor %}
				</div>
				{% endif %}
                <div class="card-body">
                    <form action="{% url 'places-new' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- This hidden input used to set the posted_by field value to the current user id -->
                        <input type="hidden" id="id_posted_by" name="posted_by" value="{{ profile.id }}">

                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-danger"><i
                                        class="fas fa-building text-light"></i></span>
                            </div>
                            <input type="text" class="form-control" id="id_name" name="name" required placeholder="Place Name">
                        </div>

                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text bg-danger"><i
                                        class="fas fa-building text-light"></i></span>
                            </div>
                            <input type="text" class="form-control" id="id_map_id" name="map_id" required placeholder="Google's Place ID">
                            
                        </div>                        
                        <small class="form-text mb-2">
                                Go to this <a href="https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder" target="_blank" class="text-secondary">link</a>, 
                                then type a location name on the map and copy <b>Place ID</b>. (picking directly doesn't work)
                        </small>

                        <div class="row">
                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-flag text-light"></i></span>
                                </div>
                                <select class="form-control" id="id_town" name="town" required>
                                    <option value="">Select Town</option>
                                    {% for option in form.fields.town.queryset %}‎
                                        <option value="{{ option.id }}">{{ option.name|capfirst }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger">
                                        <i class="fas fa-th text-light"></i>
                                    </span>
                                </div>
                                <select class="form-control" id="id_category" name="category" required>
                                    <option value="">Select Category</option>
                                    {% for option in form.fields.category.queryset %}‎
                                        <option value="{{ option.id }}">{{ option.name|capfirst }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-phone text-light"></i></span>
                                </div>
                                <input type="text" class="form-control" id="id_phone_number" name="phone_number" required placeholder="Phone Number">
                            </div>
                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fab fa-edge text-light"></i></span>
                                </div>
                                <input type="text" class="form-control" id="id_website" name="website" placeholder="Website  (Optional)">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-clock text-light"></i></span>
                                </div>
                                <input type="text" class="form-control" id="id_opening_hours" name="opening_hours" placeholder="Opening Hours (Optional)">
                            </div>

                            <div class="col-md-6 input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger">
                                        <i class="far fa-images text-light"></i>
                                    </span>
                                </div>
                                <div class="custom-file">
                                    <input type="file" name="files" class="custom-file-input" id="place-images" multiple required>
                                    <label class="custom-file-label text-truncate" for="place-images">Select Images ..</label>
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="id_description">Description</label>
                            <textarea class="form-control" style="font-size: 14px;" id="id_description" name="description" placeholder="Describe the place please.." required></textarea>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Send!" class="btn float-right login_btn btn-outline-danger"
                                style="width: 100px;">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/home/templates/home/contact.html
{% extends 'home/base.html' %}
{% block content %}
{% load static %}
    <div class="flex-grow-1" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({% static 'home/images/carousel-9.jpg' %}); background-repeat: no-repeat; background-size: cover;">
        <br>
        <div class="container text-light">
            <h2 class="py-1 border-bottom border-danger text-danger" style="border-width: 3px !important;">Contact Us</h2>
            <div>
                <p>Tourism Time</p>
                <p>Saudi Arabia, Riyadh</p>
                <p>Al-Mursalat, 12464</p>
                <p>011 454 2565</p>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d116036.07547711555!2d46.52989804541813!3d24.653744170508837!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd481df6bb18f339f!2sCommunications+and+Information+College!5e0!3m2!1sen!2ssa!4v1551439927886" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
        <br>
    </div>
{% endblock %}

src/home/templates/home/pages_section.html
<div class="pagination d-flex justify-content-center mt-4">
    <span class="step-links">
        {% if pageObj.has_previous %}
            <a href="?category={{ request.GET.category }}&page=1" class="btn btn-danger text-light">
                <i class="fas fa-angle-double-left"></i>
                first
            </a>
            <a href="?category={{ request.GET.category }}&page={{ pageObj.previous_page_number }}" class="btn btn-danger text-light">
                <i class="fas fa-angle-left"></i>
                prev
            </a>
        {% else %}
            <a href="#" class="btn btn-danger text-light disabled">
                <i class="fas fa-angle-double-left"></i>
                first
            </a>
            <a href="#" class="btn btn-danger text-light disabled">
                <i class="fas fa-angle-left"></i>
                prev
            </a>  
        {% endif %}

        <span class="current btn btn-outline-danger disabled">
            Page {{ pageObj.number }} of {{ pageObj.paginator.num_pages }}
        </span>

        {% if pageObj.has_next %}
            <a href="?category={{ request.GET.category }}&page={{ pageObj.next_page_number }}" class="btn btn-danger text-light">
                next
                <i class="fas fa-angle-right"></i>
            </a>
            <a href="?category={{ request.GET.category }}&page={{ pageObj.paginator.num_pages }}" class="btn btn-danger text-light">
                last
                <i class="fas fa-angle-double-right"></i>
            </a>
        {% else %}
            <a href="#" class="btn btn-danger text-light disabled">
                next
                <i class="fas fa-angle-right"></i>
            </a>
            <a href="#" class="btn btn-danger text-light disabled">
                last
                <i class="fas fa-angle-double-right"></i>
            </a> 
        {% endif %}
    </span>
</div>

src/home/templates/home/register.html
{% extends 'home/base.html' %}

{% block content %}
<!-- Register Content -->
<div class="flex-grow-1" id="login" style="height: 680px;">
    <div class="container h-100">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="card my-auto text-light" style="height: 360px; width: 700px;">
                <div class="card-header">
                    <h3>Sign Up</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><a href="#!"><i class="fab fa-twitter" ></i></a></span>
					<span><a href="#!"><i class="fab fa-instagram"></i></a></span>
					<span><a href="#!"><i class="fab fa-snapchat-square"></i></a></span>
				</div>
                </div>
                <div class="card-body">
                    <form method="POST" action="{% url 'home-register' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-id-card text-light"></i></span>
                                </div>
                                <input type="text" id="id_first_name" name="first_name" class="form-control" placeholder="First name" required>
                            </div>

                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-id-card text-light"></i></span>
                                </div>
                                <input type="text" id="id_last_name" name="last_name" class="form-control" placeholder="Last name" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-user text-light"></i></span>
                                </div>
                                <input type="text" id="id_username" name="username" class="form-control" placeholder="Username" required>
                            </div>

                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-envelope text-light"></i></span>
                                </div>
                                <input type="email" id="id_email" name="email" class="form-control" placeholder="Email" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-unlock-alt text-light"></i></span>
                                </div>
                                <input type="password" id="id_password" name="password" class="form-control" placeholder="Password" required>
                            </div>

                            <div class="col-md-6 input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text bg-danger"><i class="fas fa-unlock-alt text-light"></i></span>
                                </div>
                                <input type="password" id="id_p_confirm" name="p_confirm" class="form-control" placeholder="Confirm password" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Register" class="btn float-right login_btn btn-outline-danger mt-2"
                                style="width: 100px;">
                        </div>
                    </form>
                </div>
                <div class="card-footer border-danger">
                    <div class="d-flex justify-content-center text-light">
                        Already have an account?<a class="ml-2 text-secondary" href="{% url 'home-login' %}">Sign In</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}